--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem-pm-pl/UpdateChecker
build-by-default: true
branches:
- main
projects:
  UpdateChecker:
    path: ""
    model: virion
    type: library
...
